apiVersion: apps/v1
kind: Deployment 
metadata:
  name: sig-deploy
  namespace: default
  labels:
    app: sig
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: sig
  template:
    metadata:
      labels:
        app: sig 
    spec:
      containers:
      - name: sig-container 
        image: 675694928506.dkr.ecr.ap-northeast-2.amazonaws.com/eyestalk-python:v1.4.3
        ports:
        - containerPort: 5000
        env:
        - name: ES_IP
          value: "testing ES"
        - name: ES_PORT
          value: '9200'
        - name: SPRING_IP
          value: "back-svc"
        - name: SPRING_PORT
          value: '8080'
        - name: REDIS_IP
          value: "redis-svc"
        - name: REDIS_PORT
          value: '6379'
---
apiVersion: v1
kind: Service
metadata:
  name: sig-svc
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0b5818ff36bc0f4c8, subnet-0c6c725d0881c9482, subnet-07af587ef3aeeacf5, subnet-0a5ea8991f021c361
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: sig
